name: mynewz
description: MyNewZ - Get news info instantly
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.4
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  reactive_forms: ^17.0.1
  skeletonizer: ^1.4.2
  toastification: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  objectbox_generator: ^4.0.2
  very_good_analysis: ^6.0.0

objectbox:
  output_dir: core/services/objectbox

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
