name: mynewz
description: MyNewZ - Get news info instantly
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  cloud_firestore: ^5.4.4
  drift: ^2.20.3
  drift_flutter: ^0.2.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  provider: ^6.1.2
  reactive_forms: ^17.0.1

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.20.3
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
